### ISSUE TITLE
Meeting time

### ISSUE THREAD

**Issue by maryi** [maryi/CSCW-workshop4#3]
Hi team, @aliwebir @srwarnock @areyeslo @cscw2015 
I think we need to start going with the workshop... this might seem a bit early but:
The workshop is in Nov 25, however, we should present and discuss our agenda one week before. That means we need to be ready by Nov18. In addition, the week before the 18th is reading break (from 9 to 13th) and I won't be available (what about you guys, anyone going home?)....
So, we have from now until Nov 6 to do the most of the 'hard work'.. *which means we have sort of a week and a half !!* This is why I think we should start now.
Now, what about a first meeting to discuss the papers and ideas people has been suggesting?? 
I propose to have the meeting this friday (Oct 30th), my afternoon is free.
Please reply with you available time.. I'm sure we can find a space that works for everyone :)

**Comment by cscw2015** [comment]
I am available Friday afternoon. We can meet in my office (ECS613) if you like. I'm the only one who uses that office. What time were you thinking?

**Comment by areyeslo** [comment]
Perfect,we can meet in your office. To have the meeting at 2:00 pm can be nice or later if someone is busy at that time.

**Comment by maryi** [comment]
I can meet at any time on friday.. so 2pm is ok for me.

**Comment by cscw2015** [comment]
2 is good for me too.

**Comment by aliwebir** [comment]
2 pm works for me as well.

**Comment by areyeslo** [comment]
Sorry about the inconveniences, I forgot my project meeting from 2:00 pm to 4:00 pm. and I have classes from 12:30 to 1:30.. Can we meet in the morning or tomorrow (Thursday) or Monday any hour, I don't have classes those days.

**Comment by maryi** [comment]
I can meet tomorrow at 11am... Or Monday morning before 11:30am

**Comment by aliwebir** [comment]
I can make it on monday then.

**Comment by cscw2015** [comment]
I can't make it Monday until after 5:30. If everyone else can meet on Monday morning I can just put my thoughts on here and you can have the meeting anyway.

**Comment by aliwebir** [comment]
How does Monday 5:30 work for others? Actually I'm ok with Monday anytime except for 2:30-3:30

**Comment by areyeslo** [comment]
I am ok to meet on Monday at 5:30.

**Comment by maryi** [comment]
I have no problem with Monday 5:30pm :)
can we meet at your office on Monday @cscw2015 ?

**Comment by cscw2015** [comment]
Yes absolutely. Looking forward to it.

**Comment by maryi** [comment]
Ok, it's settled.
See you guys on Monday Nov 2nd at 5:30 in ECS613.

**Comment by srwarnock** [comment]
I can make it at 5:30 on Monday as well.
